# Generated by Django 5.2.3 on 2025-08-06 19:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('livres', '0003_alter_emprunt_date_emprunt_alter_emprunt_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': [('custom_perm', 'Description de la permission')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, upload_to='./images/')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CUSTOMER', 'Client')], default='CUSTOMER', max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lignepanier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lignepanier',
            name='book',
        ),
        migrations.RemoveField(
            model_name='lignepanier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('HIST', 'Histoire'), ('COME', 'Comédie'), ('RELI', 'Religion')], default='HIST', max_length=10),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En cours'), ('RETURNED', 'Rendu'), ('OVERDUE', 'En retard')], default='PENDING', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='emprunt',
            unique_together={('user', 'book')},
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['status', 'date_retour'], name='livres_empr_status_74fb04_idx'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='adherent_groups', related_query_name='adherent', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='adherent',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='adherent_permissions', related_query_name='adherent', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LignePanier',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
