# Generated by Django 5.2.3 on 2025-08-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_adherent_profile_alter_lignepanier_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adherent',
            name='user_permissions',
        ),
        migrations.RemoveIndex(
            model_name='emprunt',
            name='livres_empr_status_74fb04_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='./images/'),
        ),
        migrations.DeleteModel(
            name='Adherent',
        ),
    ]
