# Generated by Django 5.2.3 on 2025-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0006_panier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
