# Generated by Django 5.2.3 on 2025-08-20 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0009_notification_emprunt_alter_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'emprunt')},
        ),
    ]
