# Generated by Django 5.2.3 on 2025-09-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0010_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('HIST', 'Histoire'), ('COME', 'Comédie'), ('RELI', 'Religion'), ('ROM', 'Roman'), ('CL', 'Classique'), ('ST', 'Satire'), ('FICT', 'Fiction Contemporaine')], default='HIST', max_length=10),
        ),
    ]
