# Generated by Django 5.2.3 on 2025-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0011_book_description_book_rating_alter_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=4.0, max_digits=1, null=True),
        ),
    ]
