# Generated by Django 5.2.3 on 2025-09-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0012_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
